[env:arduino_uno]
;platform = espressif32
;board = esp32dev
;framework = arduino
;monitor_filters = esp32_exception_decoder
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

lib_deps =
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit BMP085 Library@^1.2.4
	adafruit/Adafruit MPU6050@^2.2.9
	olkal/HX711_ADC @ ^1.2.12