; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;-Os ; Optimiza para tamaño (en lugar de velocidad)
;    -ffunction-sections ; Elimina funciones no utilizadas
;    -fdata-sections
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Onboard computer para el cohete de ACEMA


[common]
test_framework = unity
lib_extra_dirs =
	lib/actuators
	lib/sensors
	lib/storage
	lib/transport
	lib/utils
lib_ldf_mode = deep+
lib_deps =
	madhephaestus/ESP32Servo@^3.1.3
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit MPU6050@^2.2.9
	mikalhart/TinyGPSPlus@^1.1.0
;	olkal/HX711_ADC @ ^1.2.12
	denyssene/SimpleKalmanFilter@^0.1.0
	mbed-seeed/BluetoothSerial@0.0.0+sha.f56002898ee8
	jgromes/RadioLib@^7.7.1
	tomstewart89/BasicLinearAlgebra@^5.1
build_src_filter =
	-<*>
	-<*.old>
	-<**/*.old>
	+<core/**/*.cpp>
	+<services/**/*.cpp>
monitor_filters =
;	direct,
;	colorize,
	esp32_exception_decoder
monitor_speed = 115200
test_speed = 115200     ; Velocidad del monitor durante los tests

# ============================================================================
# ENTORNO 0: Computadora de Vuelo (ESP32)
# ============================================================================

[env:esp32dev]
extends = common
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
	-D MICRO_ESP32
	-D MODULE_SX1278
;	-D DEBUG_ESP32
	-D DEBUG_DATOS_CRUDOS
	-D DEBUG_DATOS_FILTRADOS
	-I include
	-D CORE_DEBUG_LEVEL=0
build_src_filter =
	${common.build_src_filter}
	+<main.cpp>

;upload_port = /dev/ttyACM0
;monitor_port = /dev/ttyACM0
upload_port = COM4
monitor_port = COM4

# ============================================================================
# ENTORNO 1: Sensores - Debugging
# ============================================================================

[env:esp32dev-sensores]
extends = env:esp32dev

build_src_filter =
	${common.build_src_filter}
	+<main_sensores.cpp>


# ============================================================================
# ENTORNO 1: ESTACIÓN TERRENA / GSE (ESP32)
# ============================================================================
[env:GSE]
framework = arduino
platform = espressif32
board = esp32dev
build_flags =
	-D MODULE_SX1278
	-D DEBUG
	-I include
	-D CORE_DEBUG_LEVEL=3
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
test_speed = 115200     ; Velocidad del monitor durante los tests
test_framework = ${common.test_framework}
lib_ldf_mode = ${common.lib_ldf_mode}
lib_extra_dirs =
	${common.lib_extra_dirs}
lib_deps =
	${common.lib_deps}
build_src_filter =
	${common.build_src_filter}
	+<main_GSE.cpp>
upload_port = /dev/ttyUSB0  ; <-- Forzar este puerto de forma estática
monitor_port = /dev/ttyUSB0

# ============================================================================
# ENTORNO 2: COHETE / CPU (ESP32)
# ============================================================================
[env:CPU-esp32]
framework = arduino
platform = espressif32
board = esp32dev
build_flags =
	-D MICRO_ESP32
	-D MODULE_SX1278
	-I include
	-D CORE_DEBUG_LEVEL=0
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
test_speed = 115200     ; Velocidad del monitor durante los tests
test_framework = ${common.test_framework}
lib_ldf_mode = ${common.lib_ldf_mode}
lib_extra_dirs =
	${common.lib_extra_dirs}
lib_deps =
	${common.lib_deps}
build_src_filter =
	${common.build_src_filter}
	+<main_CPU.cpp>
;upload_port = /dev/ttyACM0
;monitor_port = /dev/ttyACM0
upload_port = COM4
monitor_port = COM4

# ============================================================================
# ENTORNO 3: COHETE / CPU (ARDUINO NANO)
# ============================================================================
[env:CPU-nano]
platform = atmelavr
board = nanoatmega328new
build_flags =
	-D MICRO_NANO
	-D MODULE_SX1262
lib_deps =
    ${common.lib_deps}
build_src_filter =
	${common.build_src_filter}
	+<main_CPU.cpp>
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1


# ============================================================================
# ENTORNO 2: COHETE / CPU (ESP32) / GPS
# ============================================================================
[env:CPU-GPS]
framework = arduino
platform = espressif32
board = esp32dev
build_flags =
	-D MICRO_ESP32
	-D MODULE_SX1278
	-I include          ; <-- AGREGA ESTO PARA QUE LAS LIBRERÍAS VEAN LA CARPETA INCLUDE
	-D CORE_DEBUG_LEVEL=3
lib_extra_dirs =
    ${common.lib_extra_dirs}
lib_deps =
    ${common.lib_deps}
    madhephaestus/ESP32Servo@^3.1.3
build_src_filter =
	${common.build_src_filter}
	+<main_GPS.cpp>
;upload_port = /dev/ttyUSB0
;upload_port = /dev/ttyACM0
;monitor_port = /dev/ttyACM0
upload_port = COM4
monitor_port = COM4
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
test_speed = 115200     ; Velocidad del monitor durante los tests
lib_ldf_mode = deep+    ; Fuerza a buscar a fondo en lib/ y src/

# Para compilar desde la terminar
# 	pio run -e GSE
# 	pio run -e CPU-esp32
# 	pio run -e CPU-nano
#
# Para cargar al micro
# 	pio run -e CPU-nano -t upload
#
# Ver los puertos activos en Ubuntu
#	ls /dev/ttyUSB* /dev/ttyACM*
#
# Para abrir el monitor serie
# 	pio device monitor -e CPU-esp32
#

; Entorno para testing local (muy rápido, no requiere placa conectada)
[env:native]
platform = native
test_build_src = no    ; Importante: NO compilar el src/ global
lib_ldf_mode = off     ; Desactiva la búsqueda automática de dependencias en lib/

; Construye el entorno de test con solo lo necesario

; Forzamos la inclusión de Unity para que no falle en native
lib_deps =
    https://github.com/ThrowTheSwitch/Unity.git

test_filter = test_ubx_dispatcher
; Esto incluye explícitamente el archivo de lógica que quieres probar
build_src_filter = +<../../lib/sensores/mGPS/src/UbxDispatcher.cpp> -<main_*.cpp>



; Si tus tests necesitan incluir archivos de src, asegúrate de que
; estén en el path de inclusión
build_flags = -Isrc